#!/usr/bin/python3


# Global Imports
import os
import sys


# Command imports
from Cyber_Commands import listusers, admin, userChecks, firewall


# Global Variables
commands = {
    "--listusers" : listusers.listusers,
    "--listallusers" : listusers.listallusers,
    "--isadmin" : admin.isAdmin,
    "--checkadmins" : userChecks.checkAdmins,
    "--checkusers" : userChecks.checkUsers,
    "--openfirewall" : firewall.openFirewallSettings,
    "--turnonfirewall" : firewall.turnonfirewall
}


# Collect and sort arguments
args = sys.argv
command = args[1]

args.remove(args[0])
args.remove(command)

for key in commands:
    if command == key:
        commands[key](args)
        break
